### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by posseidon23** [coin-or/MibS#59] opened 2018-06-20 00:57 UTC
Hi, 
I downloaded the Mibs package, and when trying to install on my computer (mac os X) I have the error message : 
BuildTools/get.dependencies.sh: line 656: declare: -A: invalid option
Any ideas please about the issue?
Thanks

**Comment by tkralphs** [comment] 2018-07-19 21:12
I am aware of this issue and unfortunately, I don't know of an easy fix from our side. The problem is that the version of bash that comes with OS X is very outdated. If you install a more recent version with homebrew, everything should work fine.

**Comment by posseidon23** [comment] 2018-07-19 21:58
Thank you. I ll try this.

**Comment by tkralphs** [comment] 2018-09-21 13:59
I guess this worked so I'm closing this issue.

**Closed by tkralphs** 2018-09-21 13:59 UTC
